name: interligo
description: "App Bancaria Personal - Prueba Técnica"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # BLoC Pattern
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7

  # DEPENDENCY INJECTION
  get_it: ^8.0.3

  # NAVIGATION
  go_router: ^15.1.2

  # HTTP Client
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  
  # Connectivity
  connectivity_plus: ^6.1.4
  
  # SQLite with type-safe queries (Drift)
  drift: ^2.25.0
  sqlite3_flutter_libs: ^0.5.32
  path_provider: ^2.1.5
  path: ^1.9.1
  
  # Secure Storage for tokens
  flutter_secure_storage: ^9.2.4

  # FUNCTIONAL PROGRAMMING
  
  dartz: ^0.10.1

  
  # Responsive Design
  flutter_screenutil: ^5.9.3
  
  # Typography
  google_fonts: ^6.2.1
  
  # Icons
  lucide_icons_flutter: ^1.1.8
  
  # Loading States (Skeletons)
  skeletonizer: ^2.1.2
  
  # Toasts / Notifications
  fluttertoast: ^8.2.12
  
  # Animations
  lottie: ^3.3.1

  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.1.0

  # AUTHENTICATION (OAuth2/OIDC)
  
  flutter_appauth: ^8.0.2

  # ENVIRONMENT VARIABLES
  
  flutter_dotenv: ^5.2.1

  # Date/Time formatting
  intl: ^0.20.2
  
  # UUID generation
  uuid: ^4.5.1
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  drift_dev: ^2.25.0

  # TESTING
  # Mocking
  mocktail: ^1.0.4
  
  # BLoC Testing
  bloc_test: ^10.0.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/animations/
    - assets/icons/

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700